volumes:
  prometheus_data:
  grafana_data:
  redis_data:

services:
  prometheus:
    image: prom/prometheus:v2.51.2
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - mesh-bridge
    volumes:
      - prometheus_data:/prometheus
      - ./docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    build:
      context: .
      dockerfile: ./docker/grafana/Dockerfile.grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    networks:
      - mesh-bridge
    volumes:
      - grafana_data:/var/lib/grafana
      - ./docker/grafana/datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml

  exporter:
    build:
      context: .
      dockerfile: ./docker/exporter/Dockerfile.exporter
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - .env
    networks:
      - mesh-bridge

  redis:
    image: redis:7
    restart: unless-stopped
    networks:
      - mesh-bridge
    volumes:
      - redis_data:/data

networks:
  mesh-bridge:
    driver: bridge